Add Sentry
chaosdorf/docker-stacks pull request #19
Opened 2021-02-27 19:07 UTC by YtvwlD

This PR adds Sentry as an application. I chose Sentry 20.06 because it's the one we're currently using on its own VM.

I have tested this in so far that the application can be configured, it boots and I'm able to log in to the Web UI and click around.
I couldn't test importing our previous data because I just don't have the hardware for it.

And this might be the biggest problem: Sentry seems to explode with each release (this PR adds 18 containers) and consumes quite a bit of resources even though it should do next to nothing. I'm not even sure it will run on our hardware.

Perhaps we're better off using [GlitchTip](https://glitchtip.com/)? Sadly, I didn't see an option to import data from Sentry.

2021-03-04 07:23 UTC, nomaster requested changes
Nice! I just have questions about the commented out stuff in the docker-compose file. Maybe you want a separate file for services that are only activated on demand?

Regarding the resources, can you say how much memory we need for the deployment and how much more that is compared to before?

2021-03-04 07:23 UTC, nomaster commented on enabled/sentry.yml
> +  #     - 'symbolicator:/data'
what's with this commented out stuff?

2021-03-04 07:23 UTC, nomaster commented on enabled/sentry.yml
> +  #     - redis
more commented out stuff

2021-03-04 07:23 UTC, nomaster commented on enabled/sentry.yml
> +  # symbolicator:
and a little more

2021-03-05 17:23 UTC, YtvwlD commented
The commented out stuff are optional services that we don't currently need (at least, I think so): mainly parsers for core dumps.

The software boots with 2,5GB RAM on my laptop, but that's not enough to import our old data.

2021-10-02 12:06 UTC, closed without merging